# Generated by Django 4.2.6 on 2023-10-14 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('salary', models.IntegerField()),
                ('track', models.ForeignKey(db_column='track_id', on_delete=django.db.models.deletion.CASCADE, to='track.track')),
            ],
        ),
    ]
